create table public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  phone text not null default '',
  color text not null default '#2a3647',
  created_at timestamptz not null default now(),
  is_protected boolean not null default false,
  user_id uuid unique references auth.users(id) on delete set null
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  description text,
  due_date date not null,
  priority text not null check (priority in ('urgent', 'medium', 'low')),
  category text not null check (category in ('User Story', 'Technical Task')),
  status text not null check (status in ('todo', 'in-progress', 'await-feedback', 'done')),
  position integer not null default 0 check (position >= 0),
  assigned_to bigint[],
  subtasks jsonb not null default '[]'::jsonb,
  is_protected boolean not null default false
);

create index tasks_status_position_idx on public.tasks(status, position);
create index contacts_name_idx on public.contacts(name);

alter table public.contacts enable row level security;
alter table public.tasks enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.contacts to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Authenticated users can read contacts"
on public.contacts for select to authenticated using (true);

create policy "Authenticated users can add contacts"
on public.contacts for insert to authenticated
with check (user_id is null or user_id = auth.uid());

create policy "Authenticated users can update unprotected contacts"
on public.contacts for update to authenticated
using (not is_protected)
with check (not is_protected and (user_id is null or user_id = auth.uid()));

create policy "Authenticated users can delete unprotected contacts"
on public.contacts for delete to authenticated using (not is_protected);

create policy "Authenticated users can read tasks"
on public.tasks for select to authenticated using (true);

create policy "Authenticated users can add tasks"
on public.tasks for insert to authenticated with check (not is_protected);

create policy "Authenticated users can update unprotected tasks"
on public.tasks for update to authenticated
using (not is_protected) with check (not is_protected);

create policy "Authenticated users can delete unprotected tasks"
on public.tasks for delete to authenticated using (not is_protected);

insert into public.contacts (id, name, email, phone, color, is_protected) values
  (69, 'Sofia Müller', 'sofia@example.com', '', '#00bee8', true),
  (70, 'Benedikt Ziegler', 'benedikt@example.com', '', '#9327ff', true),
  (71, 'Emanuel Mauer', 'emanuel@example.com', '', '#1fd7c1', true),
  (72, 'Marcel Bauer', 'marcel@example.com', '', '#462f8a', true),
  (73, 'Anton Mayer', 'anton@example.com', '', '#0038ff', true),
  (74, 'Anja Schulz', 'anja@example.com', '', '#ff7a00', true),
  (75, 'David Eisenberg', 'david@example.com', '', '#6e52ff', true),
  (76, 'Franziska Roth', 'franziska@example.com', '', '#fc71ff', true),
  (77, 'Hannah Vogel', 'hannah@example.com', '', '#ff5eb3', true),
  (78, 'Julia Brandt', 'julia@example.com', '', '#1fd7c1', true);

select setval(pg_get_serial_sequence('public.contacts', 'id'), 78, true);

insert into public.tasks
  (id, title, description, due_date, priority, category, status, position, assigned_to, subtasks, is_protected)
values
  (1, 'Kochwelt Page & Recipe Recommender', 'Build start page with recipe recommendation.', current_date + 14, 'medium', 'User Story', 'in-progress', 0,
   array[69,70,71,72,73,74,75,76,77,78],
   '[{"id":"subtask-1","title":"Build page structure","completed":true},{"id":"subtask-2","title":"Add recipes","completed":false}]'::jsonb, true),
  (2, 'HTML Base Template Creation', 'Create reusable HTML base templates.', current_date + 21, 'low', 'Technical Task', 'in-progress', 1,
   array[73,69,70],
   '[{"id":"subtask-3","title":"Create template","completed":true},{"id":"subtask-4","title":"Review structure","completed":true}]'::jsonb, true);

select setval(pg_get_serial_sequence('public.tasks', 'id'), 2, true);

alter publication supabase_realtime add table public.tasks;
